#include <cassert>
#include <cstdlib>
#include "CodeGen_Bash.h"
#include "Compile.h"
#include "Config.h"
#include "Parser.h"
#include "Util.h"

using namespace Bish;

namespace {

// Add necessary stdlib functions to the given module.
void link_stdlib(Bish::Module *m) {
    Parser p;
    Module *stdlib = p.parse(get_stdlib_path());
    // TODO: this seems clunky. Trying to avoid importing stdlib if
    // the user is compiling stdlib itself.
    if (m->path.compare(stdlib->path) != 0) {
        m->import(stdlib);
    }
}

}

void Bish::compile_to_bash(std::ostream &os, Module *m, bool compile_as_library) {
    link_stdlib(m);
    if (!compile_as_library) {
        os << "#!/usr/bin/env bash\n";
        os << "# Autogenerated script, compiled from the Bish language.\n";
        os << "# Bish version " << BISH_VERSION << "\n";
        os << "# Please see " << BISH_URL << " for more information about Bish.\n\n";
    }
    CodeGen_Bash compile(os, compile_as_library);
    m->accept(&compile);
}
